# Remove "scope N" from field labels. This won't remove the text if the
# remaining label is empty or very short (3 chars or less).
removeLabelScope: true

# Cleans up labels to remove special characters/excess whitespace.
cleanLabels: true

# Only process the first found table in the raw JSON tables array,
# otherwise will concatenate all matching tables into the resulting JSON.
onlyFirstTable: true

# Attempt to find & remove rows containing a numeric total value.
excludeTotalValues: true
